/**
 * THE THROWAWAY GITHUB TARGET.
 *
 * The shadow rehearsal writes to a real GitHub repo, because "Atlas edits the
 * plan body" is not proven by a shim that returns canned JSON — the interesting
 * failures live in `gh`'s actual behaviour, in what GitHub stores, and in what
 * `updatedAt` comes back as. So this module provisions a real one, and
 * `guards.ts` makes it structurally impossible for that repo to be the live
 * plan.
 *
 * ── Every call here bypasses the audit shim, on purpose ────────────────────
 * The harness spawns `gh` by ABSOLUTE PATH. Atlas's brain resolves `gh` through
 * PATH and therefore through the audit shim. The transcript
 * (`audit.ts`) is then exactly and only what ATLAS did — the harness's own
 * setup, verification and teardown never appear in it, so an assertion about
 * "every write Atlas made" cannot be diluted by the test's own writes.
 *
 * ── Nothing is deleted; everything is closed ───────────────────────────────
 * Deleting a repo needs `delete_repo`, a scope a rehearsal has no business
 * holding. So one long-lived scratch repo is reused and each run creates its own
 * fresh issues, branches and PRs, closed on the way out. A run leaves an
 * inspectable audit trail behind — which is the right default for a rehearsal
 * whose whole purpose is evidence.
 */

import { existsSync } from "node:fs";

export interface RunResult {
  ok: boolean;
  stdout: string;
  stderr: string;
}

function realGh(): string {
  const which = Bun.spawnSync(["/usr/bin/which", "gh"], { stdout: "pipe", stderr: "pipe" });
  const p = which.stdout.toString().trim().split("\n")[0] ?? "";
  if (p.length === 0 || !existsSync(p)) {
    throw new Error("shadow rehearsal: gh is not installed");
  }
  return p;
}

const GH = realGh();

export async function gh(args: string[], opts: { stdin?: string; cwd?: string } = {}): Promise<RunResult> {
  const proc = Bun.spawn([GH, ...args], {
    stdout: "pipe",
    stderr: "pipe",
    stdin: opts.stdin === undefined ? "ignore" : new TextEncoder().encode(opts.stdin),
    ...(opts.cwd === undefined ? {} : { cwd: opts.cwd }),
  });
  const [stdout, stderr, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { ok: code === 0, stdout, stderr };
}

async function ghOrThrow(args: string[], opts: { stdin?: string; cwd?: string } = {}): Promise<string> {
  const r = await gh(args, opts);
  if (!r.ok) throw new Error(`shadow rehearsal: gh ${args.join(" ")} failed: ${r.stderr.trim()}`);
  return r.stdout;
}

/** Is a usable `gh` credential present? The rehearsal refuses to guess. */
export async function ghAuthenticated(): Promise<boolean> {
  const r = await gh(["auth", "status"]);
  return r.ok;
}

export async function currentLogin(): Promise<string> {
  return (await ghOrThrow(["api", "user", "--jq", ".login"])).trim();
}

/**
 * The plan body every run starts from. Two named sections, so an ADD has
 * somewhere unambiguous to land and `apply.ts`'s `findSection` has a real
 * heading to resolve — and one pre-existing item, so `insertionPoint` is
 * exercised in its "after the last list item" branch rather than its fallback.
 */
export function seedPlanBody(runId: string): string {
  return [
    `# Shadow rehearsal plan — ${runId}`,
    "",
    "Throwaway. Generated by the Atlas shadow rehearsal harness; not a real plan.",
    "",
    "## Backend",
    "",
    "- [ ] (seed item, never touched)",
    "",
    "## Docs",
    "",
    "- [ ] (seed item, never touched)",
    "",
  ].join("\n");
}

export interface ScratchTarget {
  readonly repo: string;
  readonly planIssue: number;
  readonly planUrl: string;
  /** Open issues created for this run, in creation order. */
  readonly linked: readonly number[];
  issueUrl(n: number): string;
  planBody(): Promise<string>;
  closeIssue(n: number): Promise<void>;
  prState(number: number): Promise<{ state: string; merged: boolean } | null>;
  openPrNumbers(): Promise<number[]>;
  /** THE CONTROL: prove this credential really can merge on this repo. */
  mergeAsHarness(number: number): Promise<boolean>;
  cleanup(): Promise<void>;
}

export interface ProvisionOptions {
  /** `owner/repo`. Defaults to `<login>/atlas-shadow-rehearsal`. */
  readonly repo?: string;
  readonly runId: string;
  /** How many extra open issues to create for ADD proposals / completions. */
  readonly linkedIssues: number;
}

/** Create the scratch repo if it does not exist, and seed a `main` with a doc. */
async function ensureRepo(repo: string): Promise<void> {
  const view = await gh(["repo", "view", repo, "--json", "name"]);
  if (view.ok) return;
  await ghOrThrow([
    "repo",
    "create",
    repo,
    "--private",
    "--add-readme",
    "--description",
    "Throwaway target for the Atlas shadow rehearsal. Generated content only.",
  ]);
}

export async function provisionScratchTarget(opts: ProvisionOptions): Promise<ScratchTarget> {
  const repo = opts.repo ?? `${await currentLogin()}/atlas-shadow-rehearsal`;
  await ensureRepo(repo);

  const created: number[] = [];
  const linked: number[] = [];
  for (let i = 0; i < opts.linkedIssues; i += 1) {
    const out = await ghOrThrow([
      "issue",
      "create",
      "--repo",
      repo,
      "--title",
      `shadow ${opts.runId} — work item ${i + 1}`,
      "--body-file",
      "-",
    ], { stdin: `Throwaway work item for shadow rehearsal run ${opts.runId}.` });
    const n = Number(out.trim().split("/").pop());
    linked.push(n);
    created.push(n);
  }

  const planOut = await ghOrThrow([
    "issue",
    "create",
    "--repo",
    repo,
    "--title",
    `shadow ${opts.runId} — PLAN (throwaway)`,
    "--body-file",
    "-",
  ], { stdin: seedPlanBody(opts.runId) });
  const planIssue = Number(planOut.trim().split("/").pop());
  created.push(planIssue);

  return {
    repo,
    planIssue,
    planUrl: `https://github.com/${repo}/issues/${planIssue}`,
    linked,
    issueUrl(n: number) {
      return `https://github.com/${repo}/issues/${n}`;
    },
    async planBody() {
      return ghOrThrow(["api", `repos/${repo}/issues/${planIssue}`, "--jq", ".body"]);
    },
    async closeIssue(n: number) {
      await ghOrThrow(["issue", "close", String(n), "--repo", repo]);
    },
    async prState(number: number) {
      const r = await gh(["pr", "view", String(number), "--repo", repo, "--json", "state,mergedAt"]);
      if (!r.ok) return null;
      try {
        const o = JSON.parse(r.stdout) as { state?: unknown; mergedAt?: unknown };
        return {
          state: typeof o.state === "string" ? o.state : "UNKNOWN",
          merged: typeof o.mergedAt === "string" && o.mergedAt.length > 0,
        };
      } catch {
        return null;
      }
    },
    async openPrNumbers() {
      const r = await gh(["pr", "list", "--repo", repo, "--state", "open", "--json", "number"]);
      if (!r.ok) return [];
      try {
        const rows = JSON.parse(r.stdout) as Array<{ number: number }>;
        return rows.map((x) => x.number);
      } catch {
        return [];
      }
    },
    async mergeAsHarness(number: number) {
      // Deliberately NOT routed through Atlas. This is the control that makes
      // "Atlas's PR is still open" a statement about Atlas rather than about
      // the token's permissions.
      const r = await gh(["pr", "merge", String(number), "--repo", repo, "--squash", "--delete-branch"]);
      return r.ok;
    },
    async cleanup() {
      // Close the PRs this run opened, then every issue it created.
      const prs = await gh(["pr", "list", "--repo", repo, "--state", "open", "--json", "number,title"]);
      if (prs.ok) {
        try {
          const rows = JSON.parse(prs.stdout) as Array<{ number: number; title: string }>;
          for (const row of rows) {
            if (!row.title.includes(opts.runId)) continue;
            await gh(["pr", "close", String(row.number), "--repo", repo, "--delete-branch"]);
          }
        } catch {
          /* teardown is best effort */
        }
      }
      for (const n of created) {
        await gh(["issue", "close", String(n), "--repo", repo]);
      }
    },
  };
}
